# Generated by Django 2.0.5 on 2018-05-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('cota', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=80)),
                ('anio', models.IntegerField()),
                ('idioma', models.CharField(max_length=15)),
                ('lugar_publicacion', models.TextField()),
                ('estado', models.CharField(choices=[('P', 'Prestado'), ('B', 'Bloqueado')], max_length=1)),
            ],
        ),
    ]
