# Generated by Django 2.0.5 on 2018-05-17 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biaci_go', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=80)),
                ('cuidad', models.CharField(max_length=80)),
                ('avenida', models.CharField(max_length=80)),
                ('calle', models.CharField(max_length=80)),
                ('edificio', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('P', 'Prestado'), ('D', 'Disponible')], max_length=1)),
                ('codigo_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biaci_go.Biblioteca')),
                ('cota_recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biaci_go.Recurso')),
            ],
        ),
    ]
