# Generated by Django 2.0.5 on 2018-05-17 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biaci_go', '0003_auto_20180517_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('recurso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biaci_go.Recurso')),
                ('editorial', models.CharField(max_length=20)),
                ('isbn', models.CharField(max_length=20)),
                ('autor', models.ManyToManyField(to='biaci_go.Autor')),
            ],
            bases=('biaci_go.recurso',),
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('recurso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biaci_go.Recurso')),
                ('area', models.CharField(max_length=30)),
                ('autor', models.ManyToManyField(to='biaci_go.Autor')),
            ],
            bases=('biaci_go.recurso',),
        ),
    ]
