# Generated by Django 2.0.5 on 2018-05-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biaci_go', '0004_autor_libro_tesis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('consulta_recurso', models.ManyToManyField(to='biaci_go.Recurso')),
            ],
        ),
        migrations.CreateModel(
            name='Doctorado',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('cod_area', models.IntegerField()),
                ('num_telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=70)),
                ('direccion', models.TextField()),
                ('carrera', models.ManyToManyField(to='biaci_go.Carrera')),
                ('doctorado', models.ManyToManyField(to='biaci_go.Doctorado')),
            ],
        ),
        migrations.CreateModel(
            name='Postgrado',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('codigo_escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biaci_go.Escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('id_ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biaci_go.Ejemplar')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('id_ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biaci_go.Ejemplar')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('S', 'Suspendido'), ('B', 'Bloqueado'), ('I', 'Insolvente')], max_length=1)),
                ('contrasenia', models.CharField(max_length=50)),
                ('cedula_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biaci_go.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biaci_go.Usuario'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biaci_go.Usuario'),
        ),
        migrations.AddField(
            model_name='persona',
            name='postgrado',
            field=models.ManyToManyField(to='biaci_go.Postgrado'),
        ),
        migrations.AddField(
            model_name='persona',
            name='trabajador',
            field=models.ManyToManyField(to='biaci_go.Trabajador'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='codigo_facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biaci_go.Facultad'),
        ),
        migrations.AddField(
            model_name='doctorado',
            name='codigo_facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biaci_go.Facultad'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biaci_go.Usuario'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='codigo_escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biaci_go.Escuela'),
        ),
        migrations.AddField(
            model_name='libro',
            name='materia',
            field=models.ManyToManyField(to='biaci_go.Materia'),
        ),
    ]
